In [10]:
import numpy as np

In [11]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [12]:
x + y

array([ 7, 13, 12])

In [13]:
x = np.array ([[1 , 2], [3, 4]])

In [14]:
x.ndim

2

In [16]:
x = np.array ([[1 , 2, 3], [3, 4, 5]])

In [17]:
x.ndim

2

In [18]:
x.dtype

dtype('int64')

In [19]:
np.array?

Docstring:
array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
      like=None)

Create an array.

Parameters
----------
object : array_like
    An array, any object exposing the array interface, an object whose
    ``__array__`` method returns an array, or any (nested) sequence.
    If object is a scalar, a 0-dimensional array containing object is
    returned.
dtype : data-type, optional
    The desired data-type for the array. If not given, NumPy will try to use
    a default ``dtype`` that can represent the values (by applying promotion
    rules when necessary.)
copy : bool, optional
    If ``True`` (default), then the array data is copied. If ``None``,
    a copy will only be made if ``__array__`` returns a copy, if obj is
    a nested sequence, or if a copy is needed to satisfy any of the other
    requirements (``dtype``, ``order``, etc.). Note that any copy of
    the data is shallow, i.e., for arrays with object dtype, the new
    array will point to the 

In [20]:
x.shape

(2, 3)

In [23]:
x = np.array ([1 , 2, 3])

In [24]:
x.sum()

np.int64(6)

In [25]:
np.sum(x)

np.int64(6)

In [26]:
x = np.array ([1, 2, 3, 4, 5, 6])
print('beginning x:\n', x)
x_reshape = x.reshape ((2, 3))

beginning x:
 [1 2 3 4 5 6]


In [27]:
print('reshaped x:\n', x_reshape )

reshaped x:
 [[1 2 3]
 [4 5 6]]
