In [1]:
import numpy as np

In [4]:
x = np.array([3, 4, 5])
y = np.array([4, 9, 7])

In [5]:
x + y

array([ 7, 13, 12])

In [7]:
x = np.array([[1, 2], [3, 4]])

In [8]:
x.ndim

2

In [9]:
x.dtype

dtype('int64')

In [10]:
np.array([3.0, 4]).dtype

dtype('float64')

In [11]:
x.ndim

2

In [12]:
x.shape

(2, 2)

In [13]:
x.sum()

np.int64(10)

In [15]:
x = np.array([1, 2, 3, 4, 5, 6])
print("Beginning x:", x)
x_reshape = x.reshape((2,3)) # reshape x into 2 rows and 3 colums
print("End x:", x_reshape)

Beginning x: [1 2 3 4 5 6]
End x: [[1 2 3]
 [4 5 6]]


In [16]:
x_reshape.ndim, x_reshape.shape, x_reshape.T

(2,
 (2, 3),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [17]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974])

In [18]:
x = np.random.normal(size=50)

In [19]:
x.shape

(50,)

In [20]:
x.ndim

1

In [21]:
y = x + np.random.normal(loc=50, scale=1, size=50)

In [22]:
y

array([49.0619579 , 48.98486255, 46.92419754, 51.12741617, 48.43440906,
       49.76016275, 52.46450143, 50.13456371, 51.06683187, 52.22605807,
       51.52659033, 48.36599205, 50.20434146, 48.61270668, 49.21133067,
       51.97343878, 51.85569768, 50.36014867, 52.83921514, 50.88041477,
       50.1378081 , 52.42368552, 49.65447005, 50.60528639, 50.84929566,
       48.02833261, 49.00165041, 50.17640214, 49.27113498, 48.56244988,
       50.31965771, 51.57847452, 51.03027884, 49.30007179, 49.98906011,
       50.17993405, 51.7250141 , 49.3272869 , 51.50510946, 49.01618385,
       49.69157419, 51.24364707, 51.06329091, 50.32387596, 50.60628002,
       51.30146157, 48.8632397 , 48.81600566, 52.2073315 , 51.96864889])

In [23]:
np.corrcoef(x, y)

array([[1.        , 0.69642802],
       [0.69642802, 1.        ]])